### ISSUE TITLE
Traefik integration ?

### ISSUE THREAD

**Issue by tom-hnh** [ionorg/ion#72]
Hey,

I tried to use your docker-compose to try the project. I use traefik on my server.
I tried with this docker-compose.

```yml
version: '3.7'

services:
  ion:
    image: pionwebrtc/ion-web
    volumes:
      - "./data/Caddyfile:/etc/Caddyfile"
    expose:
      - 80
      - 8080
      - 8443
    depends_on:
      - biz
    environment:
      - WWW_URL=ion.example.com
      - ADMIN_EMAIL=john@doe.com
    networks:
      web:
      ion-net:
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ion.example.com"
      - "traefik.backend=Host:ion.example.com"
      - "traefik.port=8080"
      - "traefik.backend.port:8443"

  sfu:
    command: "-c /configs/sfu.toml"
    image: pionwebrtc/ion-sfu
    volumes:
      - "./data/sfu.toml:/configs/sfu.toml"
    ports:
      - "5000-5200:5000-5200/udp"
    depends_on:
      - nats
      - etcd
    networks:
      - web
      - ion-net

  biz:
    image: pionwebrtc/ion-biz
    command: "-c /configs/biz.toml"
    volumes:
      - "./data/biz.toml:/configs/biz.toml"
    depends_on:
      - nats
      - etcd
    networks:
      - ion-net

  islb:
    image: pionwebrtc/ion-islb
    command: "-c /configs/islb.toml"
    volumes:
      - "./data/islb.toml:/configs/islb.toml"
    depends_on:
      - nats
      - etcd
      - redis
    networks:
      - ion-net

  nats:
    image: nats
    networks: 
      - ion-net

  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.18
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
    networks:
      - ion-net 
  

  redis:
    image: redis:5.0.7
    networks:
      - ion-net

networks:
    ion-net:
    web:
      external: true
``` 

And I have modified `sfu.toml` with
```
[global]
pprof = ":6062"

# data center id
dc = "dc1"

# internet ip
addr = "ion.example.com"
```

I'm not sure I can use my domain there but I tried.

But it did not work. Any advices ?

Thanks :)
